### ISSUE TITLE
Can someone give me to create and push new branches?

### ISSUE THREAD

**Issue by airqui** [ILDAnaSoft/ILDbench_QQbar#2]
@rete @ryonamin 

Thanks!

**Comment by rete** [comment]
Done !

**Comment by airqui** [comment]
Merci! Est-ce qu'il serait possible aussi d'avoir le droit de changer le description et le branch principal? :) @rete

**Comment by rete** [comment]
Done ! Beau francais en tout cas !

**Comment by airqui** [comment]
:+1:
